seeds: [42, 137, 69]
datasets:
  # - exchange_rate # TODO this dataset will cause a problem
  # - electricity
  # - solar
  # - wiki
  # - taxi
  # - m3_monthly
  # - m3_quarterly
  # - m3_yearly
  # - m3_other
  # - m4_hourly
  # - m4_daily
  # - m4_weekly
  # - m4_monthly
  # - m4_quarterly
  # - m4_yearly
  # - m5
  # - tourism_monthly
  # - tourism_quarterly
  # - tourism_yearly
  # - nn5
  # - london_smart_meters
  # - wind_farms
  # - car_parts
  # - dominick
  # - fred_md
  # - san_francisco_traffic
  # - pedestrian_count
  # - hospital
  # - covid_deaths
  # - kdd_2018
  # - cif_2016
  # - australian_electricity_demand
  # - bitcoin
  # - rideshare
  # - vehicle_trips
  # - weather
  # - temperature_rain
  # - m1_yearly
  # - m1_quarterly
  # - m1_monthly
  # - rossmann
  # - walmart
  # - restaurant

  # freq inference problem 
  # - m1_monthly
  # - m1_quarterly
  # - m1_yearly
  # - m3_yearly
  # - m3_quarterly
  # - m3_monthly

  # rerun some error dataset 
  # - m1_monthly
  # - vehicle_trips
  # - cif_2016
  # - hospital
  # - fred_md
  # - car_parts
  # - wind_farms
  # - london_smart_meters
  # - tourism_yearly
  # - tourism_quarterly
  # - tourism_monthly
  # - m4_yearly
  # - m4_quarterly
  # - exchange_rate
  # - m3_other

  # the dataset in auto pytorch
  # - m3_yearly #segment falt
  - m3_quarterly
  - m3_monthly
  - m3_other
  - m4_quarterly
  - m4_monthly
  - m4_weekly
  - m4_daily
  - m4_hourly
  - m4_yearly
  - tourism_quarterly
  - tourism_monthly
  - dominick
  - weather
  - hospital
  - covid_deaths

  # small test dataset 
  # - solar
models:
  autogluon: 
    - key: run_time
      values: [36000]
    - key: presets
      values: [best_quality] #"best_quality"
