seeds: [42, 137, 69, 720, 24]

datasets:
  - covid_deaths
  - m3_quarterly
  - hospital
  - tourism_quarterly
  - m4_hourly
  - m3_other
  - tourism_monthly
  - m4_weekly
  - m3_monthly
  - nn5
  - electricity

models:
  arima: []
  ets: []
  npts: []
  prophet: []
  deepar:
    - key: context_length_multiple
      values: [1, 2, 4, 8]
    - key: [num_layers, num_cells]
      values: [[1, 20], [2, 40], [4, 80]]
  mqcnn:
    - key: context_length_multiple
      values: [1, 2, 4, 8]
    - key: [num_filters, kernel_size_first, kernel_size_hidden, kernel_size_last]
      values: [[20, 3, 3, 2], [30, 7, 3, 3], [40, 14, 7, 3]]
